// Package sipua wraps sipgo into the small SIP surface the daemon needs:
// a UAC that registers with Digest auth and sends MESSAGEs, plus a UAS that
// answers Catalog/DeviceInfo queries, executes control commands and handles
// INVITE/BYE sessions.
//
// The package knows nothing about GB XML bodies or media_engine; the app
// layer wires those in through Handlers.
package sipua

import (
	"context"
	"encoding/xml"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/emiago/sipgo"
	"github.com/emiago/sipgo/sip"
	"github.com/icholy/digest"
)

const contentTypeMANSCDP = "Application/MANSCDP+xml"

// Config carries the SIP identity and platform addressing.
type Config struct {
	DeviceID       string
	LocalIP        string
	ServerAddr     string // platform host:port
	PlatformID     string
	PlatformDomain string
	Password       string
	Expires        int
}

// InviteInfo is the parsed essence of an inbound INVITE.
type InviteInfo struct {
	CallID    string
	ChannelID string
	SSRC      string // raw y= value (decimal per GB28181)
	DestIP    string // where the platform expects RTP
	DestPort  int
}

// Handlers are the app-layer callbacks. All of them are optional.
type Handlers struct {
	// Query handles a platform MESSAGE (CmdType Catalog/DeviceInfo) and
	// returns the XML response body; return nil to stay silent.
	Query func(cmd, sn string) ([]byte, error)
	// Control handles a platform <Control> MESSAGE (e.g. DeviceControl with
	// PTZCmd) and returns an optional XML response body. Commands answered by
	// the 200 OK alone return nil.
	Control func(cmd, sn string, body []byte) ([]byte, error)
	// PrepareInvite validates an INVITE before the 200 is sent; an error
	// makes the UAS answer 480.
	PrepareInvite func(info InviteInfo) error
	// InviteAccepted starts media after the ACK was received.
	InviteAccepted func(info InviteInfo) error
	// Bye is called when the platform ends a session.
	Bye func(callID string)
}

// UA owns one sipgo UserAgent and shares its socket between UAC and UAS.
type UA struct {
	cfg      Config
	ua       *sipgo.UserAgent
	client   *sipgo.Client
	server   *sipgo.Server
	handlers Handlers
	log      *slog.Logger

	ackMu    sync.Mutex
	ackChans map[string]chan struct{}

	closeOnce sync.Once
}

// New creates the UA and installs the inbound request handlers.
func New(cfg Config, handlers Handlers, log *slog.Logger) (*UA, error) {
	if log == nil {
		log = slog.Default()
	}
	ua, err := sipgo.NewUA(
		sipgo.WithUserAgent(cfg.DeviceID),
		sipgo.WithUserAgentHostname(cfg.LocalIP),
	)
	if err != nil {
		return nil, fmt.Errorf("create sip user agent: %w", err)
	}
	client, err := sipgo.NewClient(ua, sipgo.WithClientHostname(cfg.LocalIP))
	if err != nil {
		_ = ua.Close()
		return nil, fmt.Errorf("create sip client: %w", err)
	}
	server, err := sipgo.NewServer(ua)
	if err != nil {
		_ = client.Close()
		_ = ua.Close()
		return nil, fmt.Errorf("create sip server: %w", err)
	}

	u := &UA{
		cfg:      cfg,
		ua:       ua,
		client:   client,
		server:   server,
		handlers: handlers,
		log:      log,
		ackChans: make(map[string]chan struct{}),
	}
	server.OnRequest(sip.MESSAGE, u.handleMessage)
	server.OnInvite(u.handleInvite)
	server.OnAck(u.handleAck)
	server.OnBye(u.handleBye)
	return u, nil
}

// Register performs REGISTER with Digest authentication and waits for 200.
func (u *UA) Register(ctx context.Context) error {
	recipient := sip.Uri{}
	if err := sip.ParseUri(fmt.Sprintf("sip:%s@%s", u.cfg.DeviceID, u.cfg.ServerAddr), &recipient); err != nil {
		return fmt.Errorf("parse register uri: %w", err)
	}
	req := sip.NewRequest(sip.REGISTER, recipient)
	req.AppendHeader(sip.NewHeader("Contact",
		fmt.Sprintf("<sip:%s@%s>;expires=%d", u.cfg.DeviceID, u.cfg.LocalIP, u.cfg.Expires)))
	req.AppendHeader(sip.NewHeader("Expires", fmt.Sprintf("%d", u.cfg.Expires)))
	req.SetTransport("UDP")

	tx, err := u.client.TransactionRequest(ctx, req, sipgo.ClientRequestRegisterBuild)
	if err != nil {
		return fmt.Errorf("register transaction: %w", err)
	}
	res, err := waitResponse(tx)
	tx.Terminate()
	if err != nil {
		return err
	}

	if res.StatusCode == 401 {
		wwwAuth := res.GetHeader("WWW-Authenticate")
		if wwwAuth == nil {
			return fmt.Errorf("register 401 without WWW-Authenticate")
		}
		chal, err := digest.ParseChallenge(wwwAuth.Value())
		if err != nil {
			return fmt.Errorf("parse digest challenge: %w", err)
		}
		cred, err := digest.Digest(chal, digest.Options{
			Method:   req.Method.String(),
			URI:      req.Recipient.String(), // request-URI after build (user cleared)
			Username: u.cfg.DeviceID,
			Password: u.cfg.Password,
		})
		if err != nil {
			return fmt.Errorf("build digest response: %w", err)
		}

		authReq := req.Clone()
		authReq.RemoveHeader("Via") // regenerated by the transport layer
		authReq.AppendHeader(sip.NewHeader("Authorization", cred.String()))
		tx2, err := u.client.TransactionRequest(
			ctx, authReq, sipgo.ClientRequestIncreaseCSEQ, sipgo.ClientRequestAddVia)
		if err != nil {
			return fmt.Errorf("authenticated register transaction: %w", err)
		}
		res, err = waitResponse(tx2)
		tx2.Terminate()
		if err != nil {
			return err
		}
	}

	if res.StatusCode != 200 {
		return fmt.Errorf("register failed: %d %s", res.StatusCode, res.Reason)
	}
	u.log.Info("registered", "device", u.cfg.DeviceID, "server", u.cfg.ServerAddr)
	return nil
}

// SendMessage sends a MESSAGE with a GB XML body to the platform.
func (u *UA) SendMessage(ctx context.Context, body []byte) error {
	recipient := sip.Uri{}
	if err := sip.ParseUri(fmt.Sprintf("sip:%s@%s", u.cfg.PlatformID, u.cfg.PlatformDomain), &recipient); err != nil {
		return fmt.Errorf("parse platform uri: %w", err)
	}
	req := sip.NewRequest(sip.MESSAGE, recipient)
	req.AppendHeader(sip.NewHeader("Content-Type", contentTypeMANSCDP))
	req.SetBody(body)
	req.SetDestination(u.cfg.ServerAddr)

	tx, err := u.client.TransactionRequest(ctx, req, sipgo.ClientRequestBuild)
	if err != nil {
		return fmt.Errorf("message transaction: %w", err)
	}
	defer tx.Terminate()
	res, err := waitResponse(tx)
	if err != nil {
		return err
	}
	if res.StatusCode != 200 {
		return fmt.Errorf("message rejected: %d %s", res.StatusCode, res.Reason)
	}
	return nil
}

// Close releases all sipgo resources.
func (u *UA) Close() {
	u.closeOnce.Do(func() {
		_ = u.server.Close()
		_ = u.client.Close()
		_ = u.ua.Close()
	})
}

func (u *UA) handleMessage(req *sip.Request, tx sip.ServerTransaction) {
	var q struct {
		XMLName xml.Name
		CmdType string `xml:"CmdType"`
		SN      string `xml:"SN"`
	}
	if err := xml.Unmarshal(req.Body(), &q); err != nil || q.CmdType == "" {
		u.log.Warn("MESSAGE without parseable CmdType", "error", err)
		_ = tx.Respond(sip.NewResponseFromRequest(req, 400, "Bad Request", nil))
		return
	}
	u.log.Info("inbound MESSAGE", "cmd", q.CmdType, "sn", q.SN, "root", q.XMLName.Local)
	_ = tx.Respond(sip.NewResponseFromRequest(req, 200, "OK", nil))

	var (
		answer []byte
		err    error
	)
	switch q.XMLName.Local {
	case "Control":
		if u.handlers.Control != nil {
			answer, err = u.handlers.Control(q.CmdType, q.SN, req.Body())
		}
	default:
		if u.handlers.Query != nil {
			answer, err = u.handlers.Query(q.CmdType, q.SN)
		}
	}
	if err != nil {
		u.log.Warn("message handler error", "cmd", q.CmdType, "root", q.XMLName.Local, "error", err)
		return
	}
	if len(answer) == 0 {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := u.SendMessage(ctx, answer); err != nil {
		u.log.Error("send query answer failed", "cmd", q.CmdType, "error", err)
	}
}

func (u *UA) handleInvite(req *sip.Request, tx sip.ServerTransaction) {
	info, err := parseInvite(req)
	if err != nil {
		u.log.Warn("parse INVITE failed", "error", err)
		_ = tx.Respond(sip.NewResponseFromRequest(req, 400, "Bad Request", nil))
		return
	}
	info.CallID = req.CallID().Value()
	u.log.Info("inbound INVITE", "callId", info.CallID, "channel", info.ChannelID,
		"target", fmt.Sprintf("%s:%d", info.DestIP, info.DestPort), "ssrc", info.SSRC)

	if u.handlers.PrepareInvite != nil {
		if err := u.handlers.PrepareInvite(info); err != nil {
			u.log.Warn("reject INVITE", "callId", info.CallID, "error", err)
			_ = tx.Respond(sip.NewResponseFromRequest(req, 480, "Temporarily Unavailable", nil))
			return
		}
	}

	answer := buildAnswerSDP(u.cfg.DeviceID, u.cfg.LocalIP, info.SSRC)
	res := sip.NewResponseFromRequest(req, 200, "OK", []byte(answer))
	res.AppendHeader(sip.NewHeader("Content-Type", "application/sdp"))
	if err := tx.Respond(res); err != nil {
		u.log.Error("respond 200 to INVITE failed", "error", err)
		return
	}

	ackCh := make(chan struct{}, 1)
	u.ackMu.Lock()
	u.ackChans[info.CallID] = ackCh
	u.ackMu.Unlock()
	defer func() {
		u.ackMu.Lock()
		delete(u.ackChans, info.CallID)
		u.ackMu.Unlock()
	}()

	select {
	case <-ackCh:
		u.log.Info("INVITE ACK received", "callId", info.CallID)
	case <-time.After(2 * time.Second):
		u.log.Warn("ACK timeout, starting media anyway", "callId", info.CallID)
	case <-tx.Done():
		u.log.Warn("INVITE transaction ended before ACK", "callId", info.CallID)
		return
	}

	if u.handlers.InviteAccepted != nil {
		if err := u.handlers.InviteAccepted(info); err != nil {
			u.log.Error("media start failed", "callId", info.CallID, "error", err)
		}
	}
}

func (u *UA) handleAck(req *sip.Request, _ sip.ServerTransaction) {
	callID := req.CallID().Value()
	u.log.Info("inbound ACK", "callId", callID)
	u.ackMu.Lock()
	ch := u.ackChans[callID]
	u.ackMu.Unlock()
	if ch != nil {
		select {
		case ch <- struct{}{}:
		default:
		}
	}
}

func (u *UA) handleBye(req *sip.Request, tx sip.ServerTransaction) {
	callID := req.CallID().Value()
	u.log.Info("inbound BYE", "callId", callID)
	_ = tx.Respond(sip.NewResponseFromRequest(req, 200, "OK", nil))
	if u.handlers.Bye != nil {
		u.handlers.Bye(callID)
	}
}

func waitResponse(tx sip.ClientTransaction) (*sip.Response, error) {
	select {
	case <-tx.Done():
		return nil, fmt.Errorf("transaction died: %v", tx.Err())
	case res := <-tx.Responses():
		return res, nil
	}
}
